name: Clean build cache

on:
  schedule:
    - cron: '21 3 * * 0' # Every Sunday at 3:21 am
  workflow_dispatch:

concurrency:
  # Cancel unfinished cleanup runs if a new run starts.
  group: clean-build-cache
  cancel-in-progress: true

jobs:
  cleanup:
    name: Cleanup GHCR build cache
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_ENV"

      - name: Cleanup container images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: >-
            ${{ env.REPO_NAME }}/build-cache,
            ${{ env.REPO_NAME }}/icons-build-cache
          older-than: 7 days
          delete-untagged: true
          delete-tags: '*'
          exclude-tags: main,latest
          delete-ghost-images: true
          delete-partial-images: true
          delete-orphaned-images: true
          dry-run: false
