name: Clean build cache

on:
  schedule:
    - cron: '21 3 * * 0' # Every Sunday at 3:21 am
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup GHCR build cache
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Cleanup container images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: build-cache
          older-than: 1 hour
          exclude-tags: main
          dry-run: true
